### ISSUE TITLE
prerequisite module for perl

### ISSUE THREAD

**Issue by ruizanthony** [erlendleganger/g2p#1]
Hi,

I tried to use g2p. It complains about a missing module in perl. Do you have a list of requirements?
Also, does g2p works with tcx files (from POLAR FLOW)(I attached the data in the zip file 16112201-Polar_Flow.zip)

+ perl /home/workingDir/pourPhilippe/g2p-master/g2p-master/bin/g2p.pl
Can't locate Log/Log4perl.pm in @INC (you may need to install the Log::Log4perl module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /home/workingDir/pourPhilippe/g2p-master/g2p-master/bin/g2p.pl line 7.
BEGIN failed--compilation aborted at /home/workingDir/pourPhilippe/g2p-master/g2p-master/bin/g2p.pl line 7.

THANKS

[16112201-Polar_Flow.zip](https://github.com/erlendleganger/g2p/files/609497/16112201-Polar_Flow.zip)

**Comment by erlendleganger** [comment]
Hello, interesting that you tried to use it. The perl modules you need are the following:
```
use XML::Parser::Expat;
use HTTP::Date;
use Data::Dumper;
use POSIX qw{strftime}; 
use Log::Log4perl qw(:levels);
```
The script converts FIT files from Garmin (currently my 920XT) to the various file formats required by Polar ProTrainer 5. It does not support TCX files.
